Persisting data in Android Edge Computing Gateway
wso2/samples-iots pull request #17
Opened 2018-02-15 09:32 UTC by LakshikaDamithri

## Purpose
Implementing a data persisting mechanism for the Android Edge Computing Gateway when the connection between the gateway and the server is lost. 
## Goals
Persisting data when the connection is lost and publishing cached data to the server when the connection is re-established. 
## Approach
Hikari CP is used to implement the JDBC connection pool so that it is possible to get and manage the database connection from the HikariCP's Datasource. When the connection is not exist data is stored in a H2 database inside the gateway. When the connection is re-established the cached data is published to the sever.
## User stories
There is separate table created for each an every sink instance.Therefore there is no need for the user to change the Android implementation every time a new device is added. And also the user can change the persist option according to their needs

## Release note
N/A

## Documentation
N/A
## Training
N/A

## Certification
N/A

## Marketing
N/A

## Automation tests
N/A

## Security checks
 - Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes
 - Ran FindSecurityBugs plugin and verified report? yes
 - Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes

## Samples
N/A

## Related PRs
N/A

## Migrations (if applicable)
N/A

## Test environment
JDK version:javac 1.8.0_144
Operating System: Linux Ubuntu
Android Studio 3.0
Android SDK Tools: 26.1.1 
Android Platform Version: API 27 revision 1

## Learning
https://medium.com/@gathikaapoorwa/embedding-siddhi-v4-0-0-in-android-d086ddafde64
https://medium.com/@gathikaapoorwa/edge-computing-for-data-driven-iot-5e345859550f
https://github.com/brettwooldridge/HikariCP

2018-03-17 09:48 UTC, rasika commented on AndroidTVGateway/agent/app/src/main/java/org/wso2/androidtv/agent/DeviceStartUpReceiver.java
> + * Copyright (c) 2017, WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
Please correct the year of the license header. Look for other places as well.

2018-03-17 09:48 UTC, rasika commented on AndroidTVGateway/agent/app/src/main/java/org/wso2/androidtv/agent/h2cache/H2Connection.java
> +        System.out.println("h2 db directory :"+directory);
Don't use System.out. Use appropriate loggers.

2018-03-17 09:48 UTC, rasika commented on AndroidTVGateway/agent/app/src/main/java/org/wso2/androidtv/agent/h2cache/H2Connection.java
> +            e.printStackTrace();
Avoid using printStackTrace(). And since method signature has `throws SQLException` you don't need to catch this unless you have something to do when you encounter an SQLException.

2018-03-17 09:48 UTC, rasika commented on AndroidTVGateway/agent/app/src/main/java/org/wso2/androidtv/agent/h2cache/H2Connection.java
> +                tableExists=true;
This is not a critical section IMO. Please re-evaluate the use of `synchronized` block

2018-03-17 09:48 UTC, rasika commented on AndroidTVGateway/agent/app/src/main/java/org/wso2/androidtv/agent/h2cache/H2Connection.java
> +            e.printStackTrace();
Avoid using printStackTrace(). You don't need to catch since method declares throws `SQLException`. Look for other places as well.

2018-03-17 09:48 UTC, rasika commented on AndroidTVGateway/agent/app/src/main/java/org/wso2/androidtv/agent/h2cache/H2Connection.java
> +        connection.close();
Possible DB connection leakage. This line won't be executed when `ps.executeUpdate();` throws an exception. `connection.close()` should be inside a `finally` closure.

2018-03-17 09:48 UTC, rasika commented on AndroidTVGateway/agent/app/src/main/java/org/wso2/androidtv/agent/mqtt/transport/MQTTTransportHandler.java
> +//    public void onConnect(MqttClient mqttc, String userdata, String flags, int result_code){
Shall we remove the commented code?

2018-03-17 09:48 UTC, rasika commented on AndroidTVGateway/agent/app/src/main/java/org/wso2/androidtv/agent/services/DeviceManagementService.java
> +//        try {
Remove commented code

2018-03-17 09:48 UTC, rasika commented on AndroidTVGateway/agent/app/src/main/java/org/wso2/androidtv/agent/siddhiSinks/EdgeGatewaySink.java
> +                            e.printStackTrace();
Avoid using `printStackTrace()`

2018-03-17 09:48 UTC, rasika commented on AndroidTVGateway/agent/app/src/main/java/org/wso2/androidtv/agent/siddhiSinks/EdgeGatewaySink.java
>              try {
Seems we have the same pattern for try{}catches{}. Use a single private method to do the validation.

2018-03-19 04:03 UTC, Nirothipan commented on AndroidTVGateway/agent/app/src/main/java/org/wso2/androidtv/agent/h2cache/DataSource.java
> +            e.printStackTrace();
Shall we use logs here

2018-03-19 04:03 UTC, Nirothipan commented on AndroidTVGateway/agent/app/src/main/java/org/wso2/androidtv/agent/h2cache/DataSource.java
> +        config.setJdbcUrl( "jdbc:h2:/data/data/org.wso2.androidtv.agent/data/edgeTVGateway;" +
Can we continue the logic if the exception happens?
Else need to move this to the catch block.

2018-03-19 04:04 UTC, Nirothipan commented on AndroidTVGateway/agent/app/src/main/java/org/wso2/androidtv/agent/h2cache/H2Connection.java
> +        System.out.println("tableExists :"+tableExists);
Better to use logs here

2018-03-19 04:05 UTC, Nirothipan commented on AndroidTVGateway/agent/app/src/main/java/org/wso2/androidtv/agent/services/DeviceManagementService.java
> +
Please remove the empty lines in all appropriate places

2018-03-19 04:05 UTC, Nirothipan commented on AndroidTVGateway/agent/app/src/main/java/org/wso2/androidtv/agent/services/SiddhiService.java
> + * Copyright (c) 2017, WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
Please fix this licence year

2018-03-19 04:06 UTC, Nirothipan commented on AndroidTVGateway/agent/app/src/main/java/org/wso2/androidtv/agent/siddhiSinks/EdgeGatewaySink.java
> +                    if(hasPersistedData){
Please format the code according to WSO2 coding styles.
there will be a space between if and (

2018-03-19 04:07 UTC, Nirothipan commented on AndroidTVGateway/agent/app/src/main/java/org/wso2/androidtv/agent/siddhiSources/TextEdgeSource.java
> + * Copyright (c) 2017, WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
Please fix this

2018-03-19 10:46 UTC, Kamidu requested changes

2018-03-19 10:46 UTC, Kamidu commented on AndroidTVGateway/agent/app/build.gradle
> +    //testImplementation 'com.h2database:h2:1.4.196'
Remove the commented lines.

2018-03-19 10:46 UTC, Kamidu commented on AndroidTVGateway/agent/app/src/main/java/org/wso2/androidtv/agent/services/DeviceManagementService.java
> +
Unwanted empty lines.

2018-03-19 10:46 UTC, Kamidu commented on AndroidTVGateway/agent/app/src/main/java/org/wso2/androidtv/agent/services/DeviceManagementService.java
> +                "topic='WINDOW',persist = 'true' , " +
maintain the same code styling/spacing.

2018-04-23 04:45 UTC, Kamidu approved these changes

2018-04-23 04:45 UTC, merged